### ISSUE TITLE
Работа экспортера из под сервисного аккаунта

### ISSUE THREAD

**Issue by b4d63rus** [unixzen/yc-billing-exporter#3]
Привет!
Очень пригодилась бы возможность работы экспортера из под сервисного аккаунта с доступом к биллинг аккаунту

**Comment by unixzen** [comment]
Привет! Переписал экспортер для работы из под сервисного аккаунта. Также добавил документацию. Все последние изменения в [ветке](https://github.com/unixzen/yc-billing-exporter/tree/feature/yc-service-account). 
Можешь проверить, если все ок, то я смержу в master.

**Comment by b4d63rus** [comment]
exec ./app: exec format error

**Comment by b4d63rus** [comment]
пересобрал своим Dockerfile, ловлю
```
time=2024-05-02T15:51:40.126Z level=INFO msg="Yandex cloud billing exporter is running..."
2024/05/02 15:51:40 INFO Build prometeus metric
2024/05/02 15:51:40 INFO Record prometeus metric
2024/05/02 15:51:40 INFO Server Started
panic: 401 Unauthorized: {
 "code": 16,
 "message": "Subject 'aje**********iee' was not found",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.RequestInfo",
   "requestId": "899893c3-6de6-479c-bcf1-23dc51ef232e"
  }
 ]
}
goroutine 33 [running]:
main.exchangeJWTToIAM({0xc00002a073?, 0x15?}, {0xc00002c007?, 0x4096ab?}, {0xc00002e010?, 0xc00012c020?})
	/build/main.go:152 +0x3be
main.recordMetrics({0xc00002a073, 0x14}, {0xc00002c007, 0x1c2}, {0xc00002e010, 0xf}, {0xc00002a03e, 0x14})
	/build/main.go:92 +0x8a
created by main.main in goroutine 1
	/build/main.go:66 +0x39b
```
"Subject 'aje**********iee' - это сам ключ сервисакка
![Uploading Снимок экрана 2024-05-02 в 19.55.33.png…]()

**Comment by unixzen** [comment]
Похоже на то, что он падает на создании JWT токена. Причина может в одном из параметров serviceAccountID, keyID, keyFile, где serviceAccountID - это ID сервисного аккаунта, keyID - это ID ключа. Вот тут есть пример ответа json, которые должен прийти при создании авторизованных ключей  https://yandex.cloud/en-ru/docs/iam/operations/authorized-key/create, вот в доке такой пример json

```
{
    "key": {
        "createdAt": "2018-10-30T15:55:00+00:00",
        "description": "",
        "id": "lfkoe35hsk58********",
        "keyAlgorithm": "RSA_2048",
        "publicKey": "-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----\n",
        "serviceAccountId": "ajepg0mjt06s********"
    },
    "privateKey": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
}
```
Вот KeyID - это id из json, который выше. 
keyFile - это файл с privateKey, из json выше.

**Comment by b4d63rus** [comment]
Взлетело (с KEY_ID косячнул), но Dockerfile вот такой применил
```
FROM golang:1.22.1-alpine3.18 as builder
WORKDIR /
COPY . .
RUN apk add --no-cache \
    ca-certificates \
    curl \
    git
RUN go build -v -o app
FROM alpine:3.19.1
WORKDIR /
RUN apk add --no-cache ca-certificates
COPY --from=builder /app .
RUN chmod +x app
CMD ["./app"]
FROM golang:1.21-alpine AS builder
RUN apk add --no-cache git
WORKDIR /build
COPY . .
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /main .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /
COPY --from=builder /main .
EXPOSE 2112
CMD ["./main"]
```
